#!/usr/bin/env python3
"""Phase B radial equation structure report.

This file does not pretend to solve the full physical branch family yet.
Its purpose is to encode the fresh-start full four-component radial matter-system
structure and the active seeding/domain convention so the Phase B runtime can be
upgraded honestly step by step.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTDIR = ROOT / "solutions" / "phase_b_radial_equation_structure"
OUTDIR.mkdir(parents=True, exist_ok=True)


def main() -> None:
    report = {
        "active_domain": {
            "omega": {"constraint": "> 0", "sample_box_used_for_scans": [0.05, 2.0]},
            "theta": [-2.0 * math.pi, 2.0 * math.pi],
            "phi": [-2.0 * math.pi, 2.0 * math.pi],
            "rho": [-2.0 * math.pi, 2.0 * math.pi],
            "quotient_redundancies": False,
        },
        "matter_radial_system": {
            "components": ["a(r)", "b(r)", "c(r)", "d(r)"],
            "norm": "|q|^2 = a^2 + b^2 + c^2 + d^2",
            "radial_ode_template": "q_A'' + (2/r + Phi' - Lambda') q_A' + exp(2 Lambda) (m_glue^2 + lambda_q |q|^2 - 2 xi R) q_A = 0",
            "component_symmetry": True,
            "couplings": ["shared norm |q|^2", "curvature scalar R", "metric functions Phi and Lambda"],
        },
        "still_missing_for_trustworthy_solver": [
            "Einstein-sector closure for m(r), Phi(r), Lambda(r), and/or R(r)",
            "explicit boundary conditions at regular origin and asymptotic region",
            "continuation parameterization / seed interpolation rule",
            "observable density formulas for mass and curvature profiles",
            "validated numerical convergence criteria",
        ],
    }
    with (OUTDIR / "report.json").open("w") as f:
        json.dump(report, f, indent=2)

    summary = []
    summary.append("# Phase B Radial Equation Structure Summary")
    summary.append("")
    summary.append("Generated by `analysis/phase_b_radial_equation_structure.py`.")
    summary.append("")
    summary.append("## Active seeding/domain convention")
    summary.append("- omega > 0 (current scan box [0.05, 2.0])")
    summary.append("- theta, phi, rho in [-2pi, 2pi]")
    summary.append("- no redundancy quotienting")
    summary.append("")
    summary.append("## Fresh-start full four-component matter system")
    summary.append("- components: a(r), b(r), c(r), d(r)")
    summary.append("- norm: |q|^2 = a^2 + b^2 + c^2 + d^2")
    summary.append("- radial ODE template:")
    summary.append("  q_A'' + (2/r + Phi' - Lambda') q_A' + exp(2 Lambda) (m_glue^2 + lambda_q |q|^2 - 2 xi R) q_A = 0")
    summary.append("")
    summary.append("## Still missing")
    for item in report["still_missing_for_trustworthy_solver"]:
        summary.append(f"- {item}")
    (OUTDIR / "summary.md").write_text("\n".join(summary))

    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
